import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative w-full flex item-center justify-center">
          <Navbar/>
          <Link href="/Contact"></Link>
          </div>
        {/* <Link href="/Contact"></Link> */}
        {children}
      </body>
    </html>
  );
}
